# -*- coding: utf-8 -*-
"""Taller_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LksSbhHL-_WtT7jIFL0emjtAHN_y16L9

# TALLER 1

## Viviana Andrea García Monje

### 1.
"""

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

#Modificar
print('---')
arr[[1,3,5,7,9]]=-1
print(arr)

#Con insertar y eliminar
arr2=np.insert(arr,(1,3,5,7,9),-1)
print('---')
print(np.delete(arr2,(2,5,8,11,14)))

"""### 2."""

import numpy as np

a2=np.arange(10)
print(a2), print('---')
a2.shape=[2,5]
print(a2)
print('-----------------------')

#Con metodo reshape
a2=np.arange(10)
print(a2), print('---')
b2=a2.reshape((2,5))
print(b2)

"""### 3."""

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.concatenate((a,b),axis=0))

"""### 4."""

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c=a[a==b]
print(c)
c=list(set(c))
print(c)

"""### 5. """

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c= np.hstack((a,b))
print(c), print('---')
print(c[0:4])

"""### 6."""

import numpy as np

a=np.array([2,6,9,10,3,27])
print(a[[1,3,4]])

"""### 7. """

arr = np.arange(9).reshape(3,3)
print(arr)
print('---')

print(arr[::-1])